Fix build Revert "DO NOT MERGE - Backport of ag/748165 to klp-dev"
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
frameworks/base/core/java/android/os/Build.java:177: error: variable BASE_OS is already defined in class VERSION
        public static final String BASE_OS = SystemProperties.get("ro.build.version.base_os", "");
                                   ^
frameworks/base/core/java/android/os/Build.java:184: error: variable SECURITY_PATCH is already defined in class VERSION
        public static final String SECURITY_PATCH = SystemProperties.get(
                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

This reverts commit a6b483722df09654cee1dc1de80a441b739c32aa.